# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Huawei Technologies Co., Ltd. All Rights Reserved.
---
- name: run omniai
  hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: true
  environment:
    LOG_PATH: /data/log_path
    LOG_PATH_IN_EXECUTOR: /data/log_path_in_executor
    CODE_PATH: /data/local_code_path
    DOCKER_IMAGE_ID: registry-cbu.huawei.com/omniai_omniinfer/ai-infra-infer-1.4.0-arm-openeuler-py311-a3-cann.9.1.t2.b020-pta_v2.9.0-op-1.2.1.post1-omni_dev_v1.0.0-vllm-202607022007:0.0.1
    DOCKER_NAME_P: "docker_name_p"
    DOCKER_NAME_D: "docker_name_d"
    DOCKER_NAME_C: "docker_name_c"
    SCRIPTS_PATH: /tmp/scripts_path

  vars:
    model: deepseek-v3.2-int8
    model_path: /sfs-asset-inference-ci/model/DeepSeek-V3.2-INT8
    run_docker_profile:
      envs:
      - PYTHONHASHSEED=123
      extra_mounts:
      - /mnt:/mnt
      - /tmp:/tmp
      - /home:/home
      - /sfs_green_wuhu_ci:/sfs_green_wuhu_ci
    sync_code_profile:
      host_sync:
        source: '{{ ansible_env.CODE_PATH }}/omniinfer'
        delete: false
      container_copy:
        prefill: "docker cp {{ ansible_env.CODE_PATH }}/omniinfer $DOCKER_NAME_P:{{ container_workspace }}/"
        decode: "docker cp {{ ansible_env.CODE_PATH }}/omniinfer $DOCKER_NAME_D:{{ container_workspace }}/"
        proxy: "docker cp {{ ansible_env.CODE_PATH }}/omniinfer $DOCKER_NAME_C:{{ container_workspace }}/"
    run_server_prefill_profile:
      runner: pd_run.sh
      prepare_commands: |-
        export SERVER_IP_LIST={{ DECODE_SERVER_IP_LIST_ALL | replace(' ', '') | trim | quote }}
        export OMNI_NPU_VLLM_PATCHES="ALL"
        export HCCL_CONNECT_TIMEOUT=1800
        export HCCL_EXEC_TIMEOUT=1800
        export HCCL_OP_RETRY_ENABLE="L0:0,L1:0,L2:0"
        export ASCEND_GLOBAL_LOG_LEVEL=3
        export VLLM_LOGGING_LEVEL="INFO"
        export HCCL_INTRA_ROCE_ENABLE="1"
        export HCCL_INTRA_PCIE_ENABLE="0"
        export VLLM_WORKER_MULTIPROC_METHOD="fork"
        export TASK_QUEUE_ENABLE=1
        export ENDPOINT_PORT={{hostvars[inventory_hostname].api_port | int + 100}}
        KV_EVENTS_CONFIG='{"enable_kv_cache_events":true,"publisher":"zmq","topic":"kv-events","endpoint":"tcp://*:'${ENDPOINT_PORT}'"}'
        export VLLM_PLUGINS="omni-npu,omni_npu_patches,omni_custom_models"

        # export VLLM_TORCH_PROFILER_DIR=/home/profiling
        # export OMNI_PROFILE_TOKEN_THRESHOLD=50
        # export OMNI_PROFILE_STOP_STEP=3
        # export OMNI_ENABLE_PREFILL_PROFILER=True
        # export OMNI_PROFILE_SKIP_REQUESTS=0

        export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True

        pip uninstall omni_placement -y
      multi_node_backend: mp
      args:
      - --max-model-len 33792
      - --gpu-util 0.9
      - --vllm-enable-mc2 1
      - >-
        --extra-args "--max-num-batched-tokens 33792 --enforce-eager
        --enable-expert-parallel --max-num-seqs 4
        --no-enable-prefix-caching --distributed-executor-backend mp
        --no-enable-chunked-prefill --dtype bfloat16
        --kv-cache-dtype bfloat16"
      - --hccl-buffsize "${HCCL_BUFFSIZE}"
      - --hccl-op-expansion-mode AIV
      - --num-speculative-tokens 0
    run_server_decode_profile:
      runner: pd_run.sh
      prepare_commands: |-
        export DECODE_DATA_PARALLEL_SIZE={{ DECODE_SERVER_BY_GROUP | quote }}
        export SERVER_IP_LIST={{ DECODE_SERVER_IP_LIST_BY_GROUP | replace(' ', '') | trim | quote }}
        export HCCL_ENTRY_LOG_ENABLE=1
        export OMNI_NPU_VLLM_PATCHES="ALL"
        export HCCL_CONNECT_TIMEOUT=1800
        export HCCL_OP_RETRY_ENABLE="L0:0,L1:0,L2:0"
        export HCCL_EXEC_TIMEOUT=1800
        export ASCEND_GLOBAL_LOG_LEVEL=3
        export VLLM_LOGGING_LEVEL="INFO"
        export HCCL_INTRA_ROCE_ENABLE="1"
        export HCCL_INTRA_PCIE_ENABLE="0"
        export VLLM_WORKER_MULTIPROC_METHOD="fork"
        # rm -rf /root/.cache/vllm/torch_compile_cache
        # export VLLM_DISABLE_COMPILE_CACHE=1
        export TASK_QUEUE_ENABLE=1
        export VLLM_PLUGINS="omni-npu,omni_npu_patches,omni_custom_models"
        # export VLLM_PLUGINS="omni-npu,omni_npu_patches"
        export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True

        # export VLLM_TORCH_PROFILER_DIR=/home/profiling
        # export OMNI_PROFILE_TOKEN_THRESHOLD=1
        # export OMNI_PROFILE_STOP_STEP=5

        # export VLLM_TORCH_PROFILER_WITH_PROFILE_MEMORY=False
        # export VLLM_TORCH_PROFILER_WITH_STACK=False
        # export VLLM_TORCH_PROFILER_WITH_FLOPS=False

        # install omni_placement
        pip uninstall omni_placement -y

        # python {{ container_workspace }}/omniinfer/tools/scripts/process_nz_config.py /usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/config/ascend910_93/aic-ascend910_93-ops-info.json
      args:
      - --max-model-len 64000
      - --tp 1
      - --gpu-util 0.9
      - --vllm-enable-mc2 1
      - >-
        --extra-args '--enable-expert-parallel --disable-log-requests
        --max-num-seqs 4 --no-enable-prefix-caching
        --distributed-executor-backend mp --dtype bfloat16
        --max-num-batched-tokens 256 --compilation-config
        {"level": 3, "cudagraph_mode": "FULL_DECODE_ONLY",
        "cudagraph_capture_sizes":[4], "backend":"eager",
        "compile_sizes":[4]}'
      - --hccl-buffsize 400
      - --hccl-op-expansion-mode AIV
      - --num-speculative-tokens 0
    run_server_common_profile:
      single_node_prefill_wait_seconds: 0
    run_proxy_profile:
      type: omni-proxy
      prepare_commands: |-
        export PYTHONHASHSEED=123
        bash {{ container_workspace }}/omniinfer/build/build.sh -m "omni-proxy"
      omni-proxy:
        args:
        - --log-file ${LOG_PATH}/{{ inventory_hostname }}/nginx_error.log
        - --log-level notice
        - --access-log-file ${LOG_PATH}/{{ inventory_hostname }}/nginx_access.log
        - --core-num 4
        - --start-core-index 16
        - --omni-proxy-pd-policy sequential
        - --omni-proxy-model-path {{ model_path | quote }}
        - --omni-proxy-max-batch-num-token 100000
        - --omni-proxy-prefill-max-num-seqs 32
        - --omni-proxy-decode-max-num-seqs 48
      global-proxy:
        args:
        - --log-file ${LOG_PATH}/{{ inventory_hostname }}/nginx_error.log
        - --log-level notice
        - --access-log-file ${LOG_PATH}/{{ inventory_hostname }}/nginx_access.log
        - --core-num 4
        - --start-core-index 16
        - --prefill-lb-sdk pd_score_balance
        - --decode-lb-sdk pd_score_balance
        - --prefill-max-num-seqs 32
        - --decode-max-num-seqs 48

  tasks:
  - ansible.builtin.import_role:
      name: common
