# Copyright (c) 2026 Huawei Technologies Co., Ltd. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Unified Pangu parser built directly on vLLM 0.25 ParserEngine."""

from __future__ import annotations

from collections.abc import Sequence

from vllm.entrypoints.openai.chat_completion.protocol import ChatCompletionRequest
from vllm.entrypoints.openai.engine.protocol import (
    DeltaMessage,
    FunctionCall,
)
from vllm.entrypoints.openai.responses.protocol import ResponsesRequest
from vllm.parser.engine.parser_engine import ParserEngine
from vllm.tool_parsers.abstract_tool_parser import ToolParser

from omni_npu import envs
from omni_npu.v1.parsers._pangu_forced_tool_parser import (
    PanguForcedToolParser,
    _mark_field_unset,
    forced_tool_name,
)
from omni_npu.v1.parsers._pangu_parser_engine_config import (
    PanguTerminals,
    pangu_parser_engine_config,
)
from omni_npu.v1.parsers._pangu_tool_array_event_expander import (
    PanguToolArrayEventExpander,
)


class PanguParserEngine(ParserEngine):
    """Parse Pangu reasoning and tool calls with one native state machine.

    Auto tool choice uses Pangu's marker-wrapped JSON array. Named and
    ``required`` choices use the raw JSON generated by structured decoding.
    """

    engine_based_streaming = True

    def __init__(self, tokenizer, tools=None, **kwargs) -> None:
        chat_kwargs = kwargs.get("chat_template_kwargs", {}) or {}
        self.thinking_enabled = not any(
            chat_kwargs.get(key) is False
            for key in ("think", "thinking", "enable_thinking")
        )
        # Prefer OMNI_PANGU_TOOL_CALL_ENDS_THINKING (start_*.sh / ansible);
        # envs also accepts the legacy alias PANGU_TOOL_CALL_ENDS_THINKING.
        self.implicit_tool_end = bool(envs.OMNI_PANGU_TOOL_CALL_ENDS_THINKING)
        self.terminals = PanguTerminals.from_tokenizer(tokenizer)
        kwargs.setdefault(
            "parser_engine_config",
            pangu_parser_engine_config(
                self.terminals,
                thinking_enabled=self.thinking_enabled,
                implicit_tool_end=self.implicit_tool_end,
            ),
        )
        super().__init__(tokenizer, tools, **kwargs)

        self._event_expander = PanguToolArrayEventExpander(self.terminals)

        # Serving uses this presence signal to pass reasoning metadata and to
        # prepare Responses structured tags. The implementation remains this
        # same unified parser; no second reasoning parser is instantiated.
        self._reasoning_parser = self
        # Keep vLLM's request-side structured-output schema generation. Output
        # parsing itself is owned by PanguForcedToolParser below.
        self._tool_parser = ToolParser(tokenizer, tools)
        self._forced_parser = PanguForcedToolParser(tokenizer)
        self._reset_forced_stream()

    def _reset(self, initial_state=None) -> None:
        super()._reset(initial_state=initial_state)
        self._event_expander.reset()
        self._forced_parser.reset()

    def _reset_forced_stream(self) -> None:
        self._forced_direct_json: bool | None = None
        self._forced_pending_text = ""
        self._forced_pending_token_ids: list[int] = []

    def _events_to_delta(self, events, finished: bool = False):
        events = self._event_expander.expand(events)
        delta = super()._events_to_delta(events, finished=finished)

        # Base ParserEngine defers content that follows tool events. At the
        # final tick there is no later delta to flush it, so preserve Pangu's
        # malformed/unclosed-wrapper fallback (and ordinary trailing text).
        if finished and self._deferred_content:
            trailing = self._deferred_content
            self._deferred_content = ""
            if delta is None:
                return DeltaMessage(content=trailing)
            delta.content = (delta.content or "") + trailing
        return delta

    def _check_skip_tool_parsing(self, request) -> None:
        tools = getattr(request, "tools", None)
        if tools:
            self._tools = tools
        skip = not tools or getattr(request, "tool_choice", None) == "none"
        self.skip_tool_parsing = skip
        self._suppress_tool_calls = skip

    def prepare_structured_tag(self, original_tag, tool_server):
        return original_tag

    def has_engine_confirmed_reasoning_end(self) -> bool:
        return self.reasoning_ended

    @staticmethod
    def _is_forced_tool_choice(
        request: ChatCompletionRequest | ResponsesRequest,
    ) -> bool:
        return (
            request.tool_choice == "required"
            or forced_tool_name(request) is not None
        )

    def adjust_request(
        self, request: ChatCompletionRequest | ResponsesRequest
    ) -> ChatCompletionRequest | ResponsesRequest:
        request = self._tool_parser.adjust_request(request)
        return super().adjust_request(request)

    def extract_reasoning(
        self,
        model_output: str,
        request: ChatCompletionRequest | ResponsesRequest,
    ) -> tuple[str | None, str | None]:
        # Forced structured decoding can start directly with JSON, without a
        # reasoning wrapper. Keep that payload out of the REASONING state.
        if self._is_forced_tool_choice(request) and model_output.lstrip().startswith(
            ("{", "[")
        ):
            return None, model_output
        return super().extract_reasoning(model_output, request)

    @staticmethod
    def _merge_delta(
        base: DeltaMessage | None,
        forced: DeltaMessage | None,
    ) -> DeltaMessage | None:
        if base is None:
            return forced
        if forced is None:
            return base
        if forced.content:
            base.content = (base.content or "") + forced.content

        if forced.tool_calls:
            forced_tools = list(forced.tool_calls)
            # Assignment is intentional: pydantic tracks it in
            # model_fields_set, so serving's exclude_unset=True keeps the
            # same-tick reasoning + first tool-call delta on the SSE wire.
            base.tool_calls = list(base.tool_calls or []) + forced_tools
        return base

    def parse(
        self,
        model_output: str,
        request: ChatCompletionRequest | ResponsesRequest,
        enable_auto_tools: bool = False,
        model_output_token_ids: Sequence[int] = (),
    ) -> tuple[str | None, str | None, list[FunctionCall] | None]:
        if not self._is_forced_tool_choice(request):
            return super().parse(
                model_output,
                request,
                enable_auto_tools=enable_auto_tools,
                model_output_token_ids=model_output_token_ids,
            )

        function_name = forced_tool_name(request)
        self._forced_parser.reset()
        reasoning, content = self.extract_reasoning(model_output, request)
        tool_calls, remaining_content = self._forced_parser.parse_complete(
            content,
            function_name,
        )
        return reasoning, remaining_content, tool_calls

    def parse_delta(
        self,
        delta_text: str,
        delta_token_ids: list[int],
        request: ChatCompletionRequest | ResponsesRequest,
        prompt_token_ids: list[int] | None = None,
        *,
        finished: bool,
    ) -> DeltaMessage | None:
        if not self._is_forced_tool_choice(request):
            return super().parse_delta(
                delta_text,
                delta_token_ids,
                request,
                prompt_token_ids,
                finished=finished,
            )

        function_name = forced_tool_name(request)
        # Buffer only until the first non-whitespace character. Direct JSON
        # bypasses the engine's default REASONING state; wrapped reasoning is
        # still split by the native ParserEngine.
        if self._forced_direct_json is None:
            self._forced_pending_text += delta_text
            self._forced_pending_token_ids.extend(delta_token_ids)
            first = self._forced_pending_text.lstrip()[:1]
            if not first and not finished:
                return None
            self._forced_direct_json = first in ("{", "[")
            delta_text = self._forced_pending_text
            delta_token_ids = self._forced_pending_token_ids
            self._forced_pending_text = ""
            self._forced_pending_token_ids = []

        if self._forced_direct_json:
            base_delta = None
            payload_delta = delta_text
        else:
            base_delta = super().parse_delta(
                delta_text,
                delta_token_ids,
                request,
                prompt_token_ids,
                finished=finished,
            )
            payload_delta = base_delta.content if base_delta else ""
            if base_delta is not None:
                # JSON payload is handed to the forced parser. Unset content
                # instead of assigning None so SSE omit the field (exclude_unset).
                _mark_field_unset(base_delta, "content")
                if not base_delta.reasoning and not base_delta.tool_calls:
                    base_delta = None

        forced_delta = self._forced_parser.parse_delta(
            payload_delta or "",
            function_name,
            finished=finished,
        )
        result = self._merge_delta(base_delta, forced_delta)

        if finished:
            self._forced_parser.reset()
            self._reset_forced_stream()
        return result
