# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Huawei Technologies Co., Ltd. All Rights Reserved.
---
- name: Create a directory on the executor to store the log.
  ansible.builtin.file:
    path: "{{ ansible_env.LOG_PATH_IN_EXECUTOR }}/{{ inventory_hostname }}"
    state: directory
  vars:
    resolved_fetch_log_profile: >-
      {{ fetch_log_profile_defaults | combine(fetch_log_profile, recursive=true) }}
  when:
    - resolved_fetch_log_profile.create_directory | bool
    - "'P' in group_names or 'D' in group_names or 'C' in group_names"
  delegate_to: localhost
  tags:
    - fetch_log

- name: Forward logs from all machines to the executor.
  ansible.builtin.synchronize:
    mode: pull
    src: "{{ ansible_env.LOG_PATH }}/{{ inventory_hostname }}/"
    dest: "{{ ansible_env.LOG_PATH_IN_EXECUTOR }}/{{ inventory_hostname }}/"
  vars:
    resolved_fetch_log_profile: >-
      {{ fetch_log_profile_defaults | combine(fetch_log_profile, recursive=true) }}
  when:
    - resolved_fetch_log_profile.fetch | bool
    - "'P' in group_names or 'D' in group_names or 'C' in group_names"
  tags:
    - fetch_log
