# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
---
- name: Run PanguV2 92B Prefill, Decode, and Omni Proxy services.
  hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: true
  environment:
    LOG_PATH: /data/log_path
    LOG_PATH_IN_EXECUTOR: /data/log_path_in_executor
    CODE_PATH: /data/local_code_path
    DOCKER_IMAGE_ID: "{{ docker_image_id }}"
    DOCKER_NAME_P: "docker_name_p"
    DOCKER_NAME_D: "docker_name_d"
    DOCKER_NAME_C: "docker_name_c"
    SCRIPTS_PATH: /tmp/scripts_path

  vars:
    model: pangu-v2-92b
    model_path: "{{ used_model_path }}/models/pangu_92B_v121/global_step_26"

    run_docker_profile:
      shm_size: 1000g
      envs:
        - PYTHONHASHSEED=1234
      extra_mounts:
        - /mnt:/mnt
        - /tmp:/tmp
        - /home:/home

    sync_code_profile:
      container_copy:
        prefill: >-
          docker exec $DOCKER_NAME_P rm -rf
          {{ container_workspace }}/omniinfer/components/omni-npu
          {{ container_workspace }}/omniinfer/components/omni-models &&
          docker exec $DOCKER_NAME_P mkdir -p
          {{ container_workspace }}/omniinfer/components &&
          docker cp {{ ansible_env.CODE_PATH }}/omni-npu
          $DOCKER_NAME_P:{{ container_workspace }}/omniinfer/components/ &&
          docker cp {{ ansible_env.CODE_PATH }}/omni-models
          $DOCKER_NAME_P:{{ container_workspace }}/omniinfer/components/
        decode: >-
          docker exec $DOCKER_NAME_D rm -rf
          {{ container_workspace }}/omniinfer/components/omni-npu
          {{ container_workspace }}/omniinfer/components/omni-models &&
          docker exec $DOCKER_NAME_D mkdir -p
          {{ container_workspace }}/omniinfer/components &&
          docker cp {{ ansible_env.CODE_PATH }}/omni-npu
          $DOCKER_NAME_D:{{ container_workspace }}/omniinfer/components/ &&
          docker cp {{ ansible_env.CODE_PATH }}/omni-models
          $DOCKER_NAME_D:{{ container_workspace }}/omniinfer/components/
        proxy: >-
          docker exec $DOCKER_NAME_C rm -rf
          {{ container_workspace }}/omniinfer/components/omni-npu
          {{ container_workspace }}/omniinfer/components/omni-models &&
          docker exec $DOCKER_NAME_C mkdir -p
          {{ container_workspace }}/omniinfer/components &&
          docker cp {{ ansible_env.CODE_PATH }}/omni-npu
          $DOCKER_NAME_C:{{ container_workspace }}/omniinfer/components/ &&
          docker cp {{ ansible_env.CODE_PATH }}/omni-models
          $DOCKER_NAME_C:{{ container_workspace }}/omniinfer/components/

    run_server_prefill_profile:
      prepare_commands: |-
        export SERVER_IP_LIST={{ DECODE_SERVER_IP_LIST_ALL | replace(' ', '') | trim | quote }}
        HCCL_BUFFSIZE=20
        export HCCL_CONNECT_TIMEOUT=1800
        export HCCL_EXEC_TIMEOUT=1800
        export HCCL_OP_RETRY_ENABLE="L0:0,L1:0,L2:0"
        export HCCL_OP_EXPANSION_MODE="AIV"
        export ASCEND_GLOBAL_LOG_LEVEL=3
        export TASK_QUEUE_ENABLE=2
        export VLLM_PLUGINS="omni-npu,omni_pangu_models,omni_npu_patches,omni_custom_models"
        export OMNI_HYBRID_ATTN_GROUP_SIZE=16
        export OMNI_NPU_PATCHES_DIR="pangu_v2_hybrid, pangu_v2_moe"
        export OMNI_NPU_VLLM_PATCHES="ALL"
        export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
        EXTRA_ARGS="--no-disable-hybrid-kv-cache-manager"
        EXTRA_ARGS="${EXTRA_ARGS} --max-num-batched-tokens 65536"
        EXTRA_ARGS="${EXTRA_ARGS} --enable-expert-parallel --max-num-seqs 32"
        EXTRA_ARGS="${EXTRA_ARGS} --enable-prefix-caching --enable-chunked-prefill"
        EXTRA_ARGS="${EXTRA_ARGS} --dtype bfloat16 --enforce-eager"
        EXTRA_ARGS="${EXTRA_ARGS} --reasoning-parser pangu"
        EXTRA_ARGS="${EXTRA_ARGS} --enable-auto-tool-choice --tool-call-parser pangu"
      args:
        - --max-model-len 524288
        - '--additional-config ''{"enable_low_latency": true}'''
        - --gpu-util 0.7
        - --extra-args "${EXTRA_ARGS}"
        - --hccl-buffsize "${HCCL_BUFFSIZE}"
        - --hccl-op-expansion-mode "${HCCL_OP_EXPANSION_MODE}"
        - --num-speculative-tokens 3

    run_server_decode_profile:
      prepare_commands: |-
        export DECODE_DATA_PARALLEL_SIZE={{ DECODE_SERVER_BY_GROUP | quote }}
        export SERVER_IP_LIST={{ DECODE_SERVER_IP_LIST_BY_GROUP | replace(' ', '') | trim | quote }}
        HCCL_BUFFSIZE=1000
        export HCCL_CONNECT_TIMEOUT=1800
        export HCCL_OP_RETRY_ENABLE="L0:0,L1:0,L2:0"
        export HCCL_EXEC_TIMEOUT=1800
        export ASCEND_GLOBAL_LOG_LEVEL=3
        export HCCL_OP_EXPANSION_MODE="AIV"
        export VLLM_PLUGINS="omni-npu,omni_pangu_models,omni_npu_patches,omni_custom_models"
        export OMNI_HYBRID_ATTN_GROUP_SIZE=16
        export OMNI_NPU_PATCHES_DIR="pangu_v2_hybrid, pangu_v2_moe"
        export OMNI_NPU_VLLM_PATCHES="ALL"
        export ENABLE_DP_LB=false
        export VLLM_CACHE_ROOT='./graph_cache'
        export TASK_QUEUE_ENABLE=1
        export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
        EXTRA_ARGS="--no-disable-hybrid-kv-cache-manager --enable-expert-parallel"
        EXTRA_ARGS="${EXTRA_ARGS} --disable-log-requests --max-num-seqs 4"
        EXTRA_ARGS="${EXTRA_ARGS} --enable-chunked-prefill --enable-prefix-caching"
        EXTRA_ARGS="${EXTRA_ARGS} --distributed-executor-backend mp"
        EXTRA_ARGS="${EXTRA_ARGS} --dtype bfloat16"
        COMPILATION_CONFIG='{"level": 3, "cudagraph_mode":"FULL_DECODE_ONLY", "cudagraph_capture_sizes":[16], "backend":"eager", "compile_sizes":[16]}'
        EXTRA_ARGS="${EXTRA_ARGS} --compilation-config ${COMPILATION_CONFIG}"
        EXTRA_ARGS="${EXTRA_ARGS} --reasoning-parser pangu"
        EXTRA_ARGS="${EXTRA_ARGS} --enable-auto-tool-choice --tool-call-parser pangu"
      args:
        - --max-model-len 524288
        - --tp 1
        - '--additional-config ''{"enable_low_latency": true}'''
        - --gpu-util 0.9
        - --extra-args "${EXTRA_ARGS}"
        - --hccl-buffsize "${HCCL_BUFFSIZE}"
        - --hccl-op-expansion-mode "${HCCL_OP_EXPANSION_MODE}"
        - --num-speculative-tokens 3

    run_proxy_profile:
      prepare_commands: |-
        export PYTHONHASHSEED=1234
        export TORCH_DEVICE_BACKEND_AUTOLOAD=0
      args:
        - --log-file ${LOG_PATH}/{{ inventory_hostname }}/nginx_error.log
        - --log-level notice
        - --access-log-file ${LOG_PATH}/{{ inventory_hostname }}/nginx_access.log
        - --core-num 4
        - --start-core-index 16
        - --omni-proxy-pd-policy sequential
        - --omni-proxy-max-batch-num-token 100000
        - --omni-proxy-prefill-max-num-seqs 32
        - --omni-proxy-decode-max-num-seqs 4

    proc_bind_profile:
      enabled: "{{ proc_bind_enabled | default(false) | bool }}"

  tasks:
    - ansible.builtin.import_role:
        name: elastic_server
