# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
---
- name: Run PanguV2 505B Prefill, Decode, and Omni Proxy services.
  hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: true
  environment:
    LOG_PATH: "/data/plj/pangu505b/log_path"
    LOG_PATH_IN_EXECUTOR: "/data/log_path_in_executor"
    CODE_PATH: "/workspace/"
    DOCKER_IMAGE_ID: "registry-cbu.huawei.com/omniai_omniinfer/ai-infra-infer-1.1.0-arm-openeuler-py311-a3-cann.8.5.1.b110-pta_2.9.0-op-1.2.1.post2-omni_release_1.1.0.post1-vllm-202607300007:0.0.1"
    DOCKER_NAME_P: "plj"
    DOCKER_NAME_D: "plj"
    DOCKER_NAME_C: "plj"
    SCRIPTS_PATH: "/tmp/scripts_path"

  vars:
    model: pangu-v2-505b
    model_path: "/mnt/sfs_turbo/bucket-910c-6055/wangzhe/iter_0009159"

    run_docker_profile:
      envs:
        - PYTHONHASHSEED=123

    sync_code_profile:
      host_sync:
        source: "{{ ansible_env.CODE_PATH }}/omniinfer"
        delete: false
      container_copy:
        prefill: >-
          docker exec $DOCKER_NAME_P rm -rf
          {{ container_workspace }}/omniinfer &&
          docker cp {{ ansible_env.CODE_PATH }}/omniinfer
          $DOCKER_NAME_P:{{ container_workspace }}/ &&
          docker exec $DOCKER_NAME_P pip uninstall -y omni-placement &&
          docker exec $DOCKER_NAME_P sh
          {{ container_workspace }}/omniinfer/components/omni-eplb/build/build.sh
        decode: >-
          docker exec $DOCKER_NAME_D rm -rf
          {{ container_workspace }}/omniinfer &&
          docker cp {{ ansible_env.CODE_PATH }}/omniinfer
          $DOCKER_NAME_D:{{ container_workspace }}/ &&
          docker exec $DOCKER_NAME_D pip uninstall -y omni-placement &&
          docker exec $DOCKER_NAME_D sh
          {{ container_workspace }}/omniinfer/components/omni-eplb/build/build.sh
        proxy: >-
          docker exec $DOCKER_NAME_C rm -rf
          {{ container_workspace }}/omniinfer &&
          docker cp {{ ansible_env.CODE_PATH }}/omniinfer
          $DOCKER_NAME_C:{{ container_workspace }}/

    pip_install_profile:
      prefill: >-
        docker exec $DOCKER_NAME_P /bin/bash -c
        '. ~/.bashrc &&
        cd {{ container_workspace }}/omniinfer/build &&
        git config --global --add safe.directory
        {{ container_workspace }}/omniinfer &&
        pip uninstall omni_infer -y &&
        bash build.sh -m "omni-npu" >
        ${LOG_PATH}/{{ inventory_hostname }}/install.log'
      decode: >-
        docker exec $DOCKER_NAME_D /bin/bash -c
        '. ~/.bashrc &&
        cd {{ container_workspace }}/omniinfer/build &&
        git config --global --add safe.directory
        {{ container_workspace }}/omniinfer &&
        pip uninstall omni_infer -y &&
        bash build.sh -m "omni-npu,omni-eplb" >
        ${LOG_PATH}/{{ inventory_hostname }}/install.log'
      proxy: >-
        docker exec $DOCKER_NAME_C /bin/bash -c
        'source ~/.bashrc &&
        cd {{ container_workspace }}/omniinfer/build &&
        bash build.sh -m "omni-proxy" >
        ${LOG_PATH}/{{ inventory_hostname }}/install.log'

    run_server_prefill_profile:
      prepare_commands: |-
        export SERVER_IP_LIST={{ DECODE_SERVER_IP_LIST_ALL | replace(' ', '') | trim | quote }}
        HCCL_BUFFSIZE=200
        export HCCL_CONNECT_TIMEOUT=1800
        export HCCL_EXEC_TIMEOUT=1800
        export HCCL_OP_RETRY_ENABLE="L0:0,L1:0,L2:0"
        export ASCEND_GLOBAL_LOG_LEVEL=3
        export TASK_QUEUE_ENABLE=1
        export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
        export HCCL_DETERMINISTIC="STRICT"
        export OMNI_CUSTOM_MODEL_CONFIG_PATH="{{ container_workspace }}/omniinfer/components/omni-npu/src/omni_npu/model_config/configs/high_throughout/openpangu_v2/openpangu_v2_505b_bf16_a3_1p1d_precision_consistency_p.json"
        export VLLM_SERVER_DEV_MODE=1
        export OMNI_NPU_PATCHES_DIR="pangu_v2_hybrid"
        export OMNI_NPU_VLLM_PATCHES="ALL"
        export VLLM_PLUGINS="omni-npu,omni_npu_patches,omni_custom_models"
        EXTRA_ARGS="--no-disable-hybrid-kv-cache-manager"
        EXTRA_ARGS="${EXTRA_ARGS} --max-num-batched-tokens 16384"
        EXTRA_ARGS="${EXTRA_ARGS} --enforce-eager --enable-expert-parallel"
        EXTRA_ARGS="${EXTRA_ARGS} --max-num-seqs 4 --enable-prefix-caching"
        EXTRA_ARGS="${EXTRA_ARGS} --dtype bfloat16"
        EXTRA_ARGS="${EXTRA_ARGS} --reasoning-parser pangu"
        EXTRA_ARGS="${EXTRA_ARGS} --enable-auto-tool-choice --tool-call-parser pangu"
      args:
        - --max-model-len 524288
        - --gpu-util 0.80
        - --extra-args "${EXTRA_ARGS}"
        - --hccl-buffsize "${HCCL_BUFFSIZE}"
        - --hccl-op-expansion-mode AIV
        - --num-speculative-tokens 3

    run_server_decode_profile:
      prepare_commands: |-
        export DECODE_DATA_PARALLEL_SIZE={{ DECODE_SERVER_BY_GROUP | quote }}
        export SERVER_IP_LIST={{ DECODE_SERVER_IP_LIST_BY_GROUP | replace(' ', '') | trim | quote }}
        HCCL_BUFFSIZE=200
        export HCCL_CONNECT_TIMEOUT=1800
        export HCCL_OP_RETRY_ENABLE="L0:0,L1:0,L2:0"
        export HCCL_EXEC_TIMEOUT=1800
        export ASCEND_GLOBAL_LOG_LEVEL=3
        export TASK_QUEUE_ENABLE=1
        export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
        export HCCL_DETERMINISTIC="STRICT"
        export OMNI_CUSTOM_MODEL_CONFIG_PATH="{{ container_workspace }}/omniinfer/components/omni-npu/src/omni_npu/model_config/configs/high_throughout/openpangu_v2/openpangu_v2_505b_bf16_a3_1p1d_precision_consistency_d.json"
        export HCCL_EP_BUFFSIZE=300
        export VLLM_SERVER_DEV_MODE=1
        export OMNI_NPU_PATCHES_DIR="pangu_v2_hybrid"
        export OMNI_NPU_VLLM_PATCHES="ALL"
        export VLLM_PLUGINS="omni-npu,omni_npu_patches,omni_custom_models"
        EXTRA_ARGS="--no-disable-hybrid-kv-cache-manager --enable-expert-parallel"
        EXTRA_ARGS="${EXTRA_ARGS} --disable-log-requests --enable-prefix-caching"
        EXTRA_ARGS="${EXTRA_ARGS} --distributed-executor-backend mp"
        EXTRA_ARGS="${EXTRA_ARGS} --dtype bfloat16 --max-num-seqs 8"
        EXTRA_ARGS="${EXTRA_ARGS} --max-num-batched-tokens 32"
        COMPILATION_CONFIG='{"level": 3, "cudagraph_mode":"FULL", "backend":"eager", "cudagraph_capture_sizes":[4,16,32], "compile_sizes":[4,16,32]}'
        EXTRA_ARGS="${EXTRA_ARGS} --compilation-config ${COMPILATION_CONFIG}"
        EXTRA_ARGS="${EXTRA_ARGS} --reasoning-parser pangu"
        EXTRA_ARGS="${EXTRA_ARGS} --enable-auto-tool-choice --tool-call-parser pangu"
      args:
        - --max-model-len 524288
        - --tp 1
        - --gpu-util 0.80
        - --extra-args "${EXTRA_ARGS}"
        - --hccl-buffsize "${HCCL_BUFFSIZE}"
        - --hccl-op-expansion-mode AIV
        - --num-speculative-tokens 3

    run_proxy_profile:
      prepare_commands: |-
        export PYTHONHASHSEED=123
      args:
        - --log-file ${LOG_PATH}/{{ inventory_hostname }}/nginx_error.log
        - --log-level notice
        - --access-log-file ${LOG_PATH}/{{ inventory_hostname }}/nginx_access.log
        - --core-num 4
        - --start-core-index 16
        - --omni-proxy-pd-policy sequential
        - --omni-proxy-model-path {{ model_path | quote }}
        - --omni-proxy-max-batch-num-token 100000
        - --omni-proxy-prefill-max-num-seqs 1
        - --omni-proxy-decode-max-num-seqs 8

    proc_bind_profile:
      enabled: "{{ proc_bind_enabled | default(false) | bool }}"

    fetch_log_profile:
      create_directory: false
      fetch: false

  tasks:
    - ansible.builtin.import_role:
        name: elastic_server
